
SET IDENTITY_INSERT CATALOGO_DESCUENTO ON

insert into CATALOGO_DESCUENTO (ID_DESCUENTO,NOMBRE_DESCUENTO,DELEY_DESCUENTO) VALUES (1,'AFP',1);
insert into CATALOGO_DESCUENTO (ID_DESCUENTO,NOMBRE_DESCUENTO,DELEY_DESCUENTO) VALUES (2,'ISSS',1);

SET IDENTITY_INSERT CATALOGO_DESCUENTO off
